### ISSUE TITLE
Disclaimer about what happens to the photos uploaded

### ISSUE THREAD

**Issue by losowsky** [voxmedia/tonr#4]
It'd be great for privacy reasons to see a note beneath "Select photo" explaining exactly what happens to photos we upload. Are they stored anywhere on your side? Do you delete them after a certain amount of time?

**Comment by aidanfeay** [comment]
@losowsky Thanks for submitting an issue! Does the copy feel more straightforward now?

**Comment by losowsky** [comment]
Perfect, thanks Aidan.
